import Graph from "./graph/graph.js";

export default function buildGraph() {
  const graph = new Graph();

  // Put unconnected nodes ind i grafren
  graph.addNode("a", 43, 43);
  graph.addNode("b", 43, 140);
  graph.addNode("c", 43, 235);
  graph.addNode("d", 43, 390);
  graph.addNode("e", 43, 480);
  graph.addNode("f", 140, 43);
  graph.addNode("g", 140, 140);
  graph.addNode("h", 140, 235);
  graph.addNode("i", 190, 390);
  graph.addNode("j", 190, 480);
  graph.addNode("k", 235, 43);
  graph.addNode("l", 235, 140);
  graph.addNode("m", 235, 235);
  graph.addNode("n", 335, 43);
  graph.addNode("o", 335, 140);
  graph.addNode("p", 335, 235);
  graph.addNode("q", 335, 390);
  graph.addNode("r", 335, 480);
  graph.addNode("s", 430, 43);
  graph.addNode("t", 430, 235);
  graph.addNode("u", 430, 390);
  graph.addNode("v", 430, 480);
  graph.addNode("w", 525, 43);
  graph.addNode("x", 525, 235);
  graph.addNode("y", 525, 390);
  graph.addNode("z", 625, 43);
  graph.addNode("æ", 625, 140);
  graph.addNode("ø", 625, 235);
  graph.addNode("å", 625, 390);
  graph.addNode("α", 625, 480);
  graph.addNode("β", 720, 43);
  graph.addNode("γ", 720, 140);
  graph.addNode("δ", 720, 235);
  graph.addNode("ε", 720, 390);
  graph.addNode("ζ", 720, 480);

  // Lav links imellem grafens nodes
  graph.addLink("a", "b");
  graph.addLink("a", "f");
  graph.addLink("b", "a");
  graph.addLink("b", "c");
  graph.addLink("b", "g");
  graph.addLink("c", "b");
  graph.addLink("c", "d");
  graph.addLink("c", "h");
  graph.addLink("d", "c");
  graph.addLink("d", "e");
  graph.addLink("d", "i");
  graph.addLink("e", "d");
  graph.addLink("e", "j");
  graph.addLink("f", "a");
  graph.addLink("f", "g");
  graph.addLink("f", "k");
  graph.addLink("g", "b");
  graph.addLink("g", "f");
  graph.addLink("g", "h");
  graph.addLink("g", "l");
  graph.addLink("h", "c");
  graph.addLink("h", "g");
  graph.addLink("h", "i");
  graph.addLink("h", "m");
  graph.addLink("i", "d");
  graph.addLink("i", "h");
  graph.addLink("i", "j");
  graph.addLink("i", "p");
  graph.addLink("j", "e");
  graph.addLink("j", "i");
  graph.addLink("j", "r");
  graph.addLink("k", "f");
  graph.addLink("k", "l");
  graph.addLink("k", "n");
  graph.addLink("l", "g");
  graph.addLink("l", "k");
  graph.addLink("l", "m");
  graph.addLink("l", "o");
  graph.addLink("m", "h");
  graph.addLink("m", "l");
  graph.addLink("m", "p");
  graph.addLink("n", "k");
  graph.addLink("n", "o");
  graph.addLink("n", "s");
  graph.addLink("o", "l");
  graph.addLink("o", "n");
  graph.addLink("o", "p");
  graph.addLink("o", "æ");
  graph.addLink("p", "m");
  graph.addLink("p", "o");
  graph.addLink("p", "q");
  graph.addLink("q", "i");
  graph.addLink("q", "p");
  graph.addLink("q", "r");
  graph.addLink("r", "j");
  graph.addLink("r", "q");
  graph.addLink("r", "v");
  graph.addLink("s", "n");
  graph.addLink("s", "t");
  graph.addLink("s", "w");
  graph.addLink("t", "u");
  graph.addLink("t", "x");
  graph.addLink("u", "q");
  graph.addLink("u", "t");
  graph.addLink("u", "v");
  graph.addLink("v", "r");
  graph.addLink("v", "u");
  graph.addLink("v", "α");
  graph.addLink("w", "s");
  graph.addLink("w", "x");
  graph.addLink("w", "z");
  graph.addLink("x", "t");
  graph.addLink("x", "w");
  graph.addLink("x", "ø");
  graph.addLink("y", "u");
  graph.addLink("y", "x");
  graph.addLink("y", "å");
  graph.addLink("z", "w");
  graph.addLink("z", "æ");
  graph.addLink("z", "β");
  graph.addLink("æ", "o");
  graph.addLink("æ", "z");
  graph.addLink("æ", "ø");
  graph.addLink("æ", "γ");
  graph.addLink("ø", "x");
  graph.addLink("ø", "æ");
  graph.addLink("ø", "å");
  graph.addLink("ø", "δ");
  graph.addLink("å", "ø");
  graph.addLink("å", "α");
  graph.addLink("å", "ε");
  graph.addLink("α", "v");
  graph.addLink("α", "å");
  graph.addLink("α", "ζ");
  graph.addLink("β", "z");
  graph.addLink("β", "γ");
  graph.addLink("γ", "æ");
  graph.addLink("γ", "β");
  graph.addLink("γ", "δ");
  graph.addLink("δ", "ø");
  graph.addLink("δ", "γ");
  graph.addLink("δ", "ε");
  graph.addLink("ε", "å");
  graph.addLink("ε", "δ");
  graph.addLink("ε", "ζ");
  graph.addLink("ζ", "α");
  graph.addLink("ζ", "ε");

  return graph;
}
